### ISSUE TITLE
Pr.2: en tu subtarea cuantosPokDeTipo_LeGananATodosLosPok_ hay un caso innecesario

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#15]
Si no estás haciendo recursión sobre una lista, en la mayoría de los casos es innecesario ver el caso de lista vacía, este es uno de esos casos. De hecho, quitando el caso tu función debería solucionar de la misma manera.

**Comment by nasrcristian** [comment]
Hecho.

**Comment by FrancoMarengo** [comment]
Bien!
