### ISSUE TITLE
Pr.2: en proyectosDeCadaRol no estás usando recursión estructural

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#16]
Si bien no está mal utilizar subtareas, esta es una práctica de recursión estructural, y la idea es que las puedan hacer con recursión estructural, en aquellos casos que se pueda (como este).
Evitá utilizar append (++) y por ende evitá utilizar singularSi en este caso y similares. Esta bastante bien pero con otras subtareas sale más fácil y sin necesidad de utilizar (++).

**Comment by nasrcristian** [comment]
Hecho.

**Comment by FrancoMarengo** [comment]
Bien, esta casi listo, pero fijate que tu función calcula dos veces la recursión, una en el if como condición, y otra en el then-else. Como se resuelve esto? Con un let o con una subtarea que te sirva para eliminar el if-then-else de ahi y por ende, de calcular dos veces el llamado recursivo. El "let in" sirve para calcular una variable una unica vez y usarla dentro de una porción de código:
let nombreVariable = llamadoRecursivoA xs in
{ Aca va el codigo del if-then-else usando la variable o lo que quieras }
De esta manera decis "calcula esta variable y llamala nombreVariable" y después la usas donde querés, en la condición y en las ramas then-else por ejemplo, y evitaste de que tu función calcule mas de una vez la recursión

**Comment by nasrcristian** [comment]
No conocía acerca del "let in", ya lo implementé. Gracias!

**Comment by FrancoMarengo** [comment]
Es muy útil ahora y mas adelante te va a ayudar mucho. También se puede resolver con una subtarea para eliminar el if-then-else como te dije, pero asi está perfecto y esta bien que lo utilicen (en los casos que corresponda, no de manera excesiva).
