### ISSUE TITLE
Pr.2: tu solución de losDevSenior tiene en cuenta casos que no debería

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#17]
Tu solución esta muy bien, pero no solo tiene en cuenta casos de "Developer Senior", tiene en cuenta otros roles.

**Comment by nasrcristian** [comment]
Hecho.

**Comment by FrancoMarengo** [comment]
Bien, pero ahora estas haciendo doble pattern matching, una sobre Rol y otra sobre Seniority, lo tenías bien antes porque tenías una subtarea (esSenior) que recibía un tipo de Seniority e indicaba si era Senior. Ahora tenés todo junto, calculas que sea Developer Senior y esto no está bien porque acumulas responsabilidades en losDevSenior, primero ves si es developer y de ahi ves si es senior.

**Comment by nasrcristian** [comment]
Hecho, no sabia si eran muchas condiciones juntas en el if por eso fui por la otra opción. Pero ya lo arreglé, gracias.

**Comment by FrancoMarengo** [comment]
No hacía falta que lo pongas en el if, iba mas por el lado que hagas lo siguiente:
esDevSenior (Developer s _) = esSenior s
esDevSenior _                       = False

esSenior Senior = True
esSenior _          = False

De esta manera evitabas acumular responsabilidades en esDevSenior, pero como lo hiciste es correcto, evitas acumular todo en una función y por ende cumpliste.
