### ISSUE TITLE
Pr.3: tu funcion alMenosNTesoros no es del todo correcta

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#19]
No tenés en cuenta la cantidad de tesoros que puedan haber dentro de un cofre, es decir, si pedimos al menos 4 tesoros y un cofre contiene 4 tesoros, entonces la función debería retornar True, pero tu resolución no mira la cantidad dentro del cofre.

**Comment by nasrcristian** [comment]
Hecho.

**Comment by FrancoMarengo** [comment]
Mejor, pero ahora si tenés un cofre con mas tesoros de los pedidos, terminas llamando a tu recursión con un número negativo y esto provoca que recorras todo el camino restante procesando cofres para llegar a Fin únicamente para devolver False porque "n" es un número negativo y no 0
