### ISSUE TITLE
Pr.3: en simplificar las funciones auxiliares tienen una cantidad incorrecta de parámetros

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#21]
No es feliz reconstruir algo que vas a deconstruir inmediatamente... Deberían tener 2 argumentos (y así las llamaste...)
En "simplificar (Sum exp1 exp2) = simplificarPorNumeroNeutro (Sum (simplificar exp1) (simplificar exp2))" estas armando la suma nuevamente cuando podrías pasarle las dos expresiones.

**Comment by FrancoMarengo** [comment]
Muchísimo mejor. Ahora, tu simplificar no solo simplifica, si no que también evalua las expresiones y esto no es correcto, solo se pide simplificar, esto se da porque en tus subtareas usas eval. Tip: Hace tus subtareas por pattern matching, si querés ver que un valor es 0 en simplificarSumaNeutra te fijas si alguna ExpA es (Valor 0)

**Comment by nasrcristian** [comment]
Así sería correcto? Yo lo había interpretado como que simplifique si el resultado de una de las dos expresiones daba 0 (o 1 en el caso de producto)
