### ISSUE TITLE
Pr.3: en simplificar podrías dividir en subtareas mejor

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#22]
Si bien resuelve correctamente, estaría muchísimo mejor sacar todos los IFs y dividir en distintas subtareas que hagan PM sobre las expresiones, de lo contrario es muy complicado de leer y razonar.

**Comment by nasrcristian** [comment]
Eliminé varios de los IFs, pero deje algunos que me parece que quedan mejor que haciendo PM. No sabría si así está correcto..

**Comment by FrancoMarengo** [comment]
Como mencioné en el anterior issue, es mejor hacerlo por PM, ahora está mejor dividido en subtareas así que este issue esta resuelto.
