### ISSUE TITLE
Pr.1: hay pattern matching innecesario en la funcion esMayorQueLaOtra

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#5]
Solamente hay que hacer PM cuando querés acceder a las partes o validar que algo está hecho con determinado constructor. No tiene sentido hacer PM para luego usarlo exactamente igual del otro lado. Por ejemplo:
    cantidadDePokemonDe tipoPokemon (E n p1 p2) =
    contarPokemonSi (tipoPokemon) (pokemonsPorEntrenador (E n p1 p2))
es exactamente lo mismo que
    cantidadDePokemonDe tipoPokemon e = 
       contarPokemonSi (tipoPokemon) (pokemonsPorEntrenador e)
Es una mala práctica usar herramientas que no necesitás.

**Comment by nasrcristian** [comment]
Hecho.
