### ISSUE TITLE
Pr.1: las funciones laQueEsMayor y p1SiVerdaderoP2SiNo hacen pattern matching innecesario

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#6]
Solamente hay que hacer PM cuando querés acceder a las partes o validar que algo está hecho con determinado constructor. No tiene sentido hacer PM para luego usarlo exactamente igual del otro lado. Además, ya tenés una subtarea definida que retorna un booleano comparando edades de personas, estas repitiendo tarea que tenés resuelta. Por último, no es necesaria la función p1SiVerdaderoP2SiNo, ya que podría desaparecer si usamos un if-then-else en la función laQueEsMayor. Enfocate en resolver de manera simple y eficiente esta última.

**Comment by nasrcristian** [comment]
Hecho.
