### ISSUE TITLE
Pr.1: La función unoSiEsTipoCeroSiNo tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by FrancoMarengo** [nasrcristian/EstrD2023s1#7]
Podés separarla en dos funciones, cada una de las cuales haga la parte que le toca (y así, conservando el nombre unoOCero para esta función, o uno similar (mejor es el visto en Intro...). Además, estas haciendo pattern matching en esta función, no sería mejor tener una función que se encargue de comparar tipos?

**Comment by nasrcristian** [comment]
Hecho.

**Comment by FrancoMarengo** [comment]
Bien, pero fijate que tu función esDeTipo estaría mucho mejor si pudieras pasarle dos TipoDePokemon y no un Pokemon y un TipoDePokemon. Te evita hacer casos de pattern matching sobre Pokemon

**Comment by nasrcristian** [comment]
Hecho. Estaba en duda respecto a este ejercicio y no sabia si era correcto comparar dos TipoDePokemon. Pero supongo que el criterio sería evitar hacer estos pattern matching innecesarios.

**Comment by FrancoMarengo** [comment]
Si, es correcto comparar dos tipos de Pokémon siempre y cuando no uses el igual (==). El criterio pasa por no hacer pattern matching innecesario y por tener una subtarea clara que tenga una única responsabilidad.
